### ISSUE TITLE
statespace_limits with Tabular and IncrTabular issue

### ISSUE THREAD

**Issue by silgon** [rlpy/rlpy#3]
Hi, I've been testing rlpy already some days. I've encountered a problem when I wanted to put different `statespace_limits` in my domain. When the values in different dimensions are not the same, it just doesn't work. I tried with RBF and Fourier and I don't have that problem. I add the space limit I use:

```python
 statespace_limits = np.array([[-10., 10.], [-5, 5]])  # not working
 # statespace_limits = np.array([[-10., 10.], [-10., 10.]]) # working
```
And I add the error trace so you can see it.

```
Traceback (most recent call last):
  File "test.py", line 103, in <module>
    visualize_performance=False)  # show performance runs?
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Experiments/Experiment.py", line 350, in run
    self.evaluate(total_steps, episode_number, visualize_performance)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Experiments/Experiment.py", line 445, in evaluate
    total_steps, visualize=visualize > j)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Experiments/Experiment.py", line 212, in performanceRun
    a = self.agent.policy.pi(s, eps_term, p_actions)
  File "/home/aronnax/dev/rlpy_test/tuto/eGreedyTut.py", line 26, in pi
    b_actions = self.representation.bestActions(s, terminal, p_actions)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Representation.py", line 358, in bestActions
    Qs = self.Qs(s, terminal, phi_s)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Representation.py", line 170, in Qs
    phi_s = self.phi(s, terminal)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Representation.py", line 222, in phi
    return self.phi_nonTerminal(s)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Tabular.py", line 31, in phi_nonTerminal
    hashVal = self.hashState(s)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Representation.py", line 299, in hashState
    ds = self.binState(s)
  File "/usr/local/lib/python2.7/dist-packages/rlpy/Representations/Representation.py", line 335, in binState
    assert (np.all(s >= limits[:, 0]))
AssertionError
```

**Comment by chrodan** [comment]
Thanks for reporting. I have trouble reproducing this issue. Can you provide a minimal working example?
